[package]
name = "bob-nvim"
edition = "2021"
version = "0.0.19"
description = "A version manager for neovim"
readme = "README.md"
keywords = ["neovim", "version-manager"]
categories = ["command-line-utilities"]
license = "MIT"
repository = "https://github.com/MordechaiHadad/bob"