name: Release

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "hi" >> yo.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact1.zip
          path: yo.txt
  
  build-1:
    runs-on: ubuntu-latest
    steps:
      - name: Build again
        run: echo "brooo :(" >> damn.txt
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: artifact2.zip
          path: damn.txt

  release:
    needs: [build, build-1]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: List files
        run: ls -la artifacts/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/*.zip