name: Release

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check version
        id: check_version
        run: |
          VERSION=v$(grep '^version =' Cargo.toml | cut -d '"' -f 2)
          GIT_TAG_VERSION=${{ github.ref }} 
          GIT_TAG_VERSION=${GIT_TAG_VERSION#refs/tags/}
          if [[ "$VERSION" != "$GIT_TAG_VERSION" ]]; then
            echo "Version in Cargo.toml ($VERSION) does not match pushed tag ($GIT_TAG_VERSION)"
            exit 1
          fi
      

  build:
    needs: check-version
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "hi" >> yo.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact1
          path: yo.txt
  
  build-1:
    needs: check-version
    runs-on: ubuntu-latest
    steps:
      - name: Build again
        run: echo "brooo :(" >> damn.txt
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: artifact2
          path: damn.txt

  release:
    needs: [build, build-1]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: --verbose --current
        env:
          OUTPUT: CHANGELOG.md
      - name: Zip artifacts
        run: |
          cd artifacts
          for dir in */; do
            base=$(basename "$dir")
            zip -r "${base}.zip" "$dir"
          done
      - name: Get current dir
        run: | 
          echo $PWD
          ls
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          files: |
            ./artifacts/*.zip